AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 400

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 1500

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: "inject"

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/RaiseArgs:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Lint/SuppressedException:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Naming/BinaryOperatorParameterName:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 200

RSpec/MultipleMemoizedHelpers:
  Enabled: true

require:
  - rubocop-rspec
  - rubocop-factory_bot